name: reminder_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: ^4.0.3
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  timezone: ^0.9.3
  intl: ^0.19.0
  logger: ^2.3.0
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
